import type { Task } from './types';

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Finalize Q3 marketing strategy',
    description: 'Review the proposal from the content team, check the budget, and create a presentation for the stakeholders meeting on Friday.',
    completed: false,
    priority: 'high',
    tags: ['marketing', 'strategy'],
    dueDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    pomodoros: 4,
    completedPomodoros: 1,
    timeSpent: 720,
    workspace: 'work',
    dependsOn: [],
    completedDate: undefined,
  },
  {
    id: 'task-2',
    title: 'Develop user authentication feature',
    description: 'Implement JWT-based authentication for the main application. Include sign-up, login, and password-reset flows.',
    completed: false,
    priority: 'high',
    tags: ['development', 'feature'],
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    pomodoros: 8,
    completedPomodoros: 0,
    timeSpent: 0,
    dependsOn: ['task-4'],
    workspace: 'work',
    completedDate: undefined,
  },
  {
    id: 'task-3',
    title: 'Update component library documentation',
    description: 'Add examples and usage guidelines for the new Button and Card components. Ensure all props are documented.',
    completed: true,
    priority: 'medium',
    tags: ['docs', 'design-system'],
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)),
    pomodoros: 3,
    completedPomodoros: 3,
    timeSpent: 5400,
    workspace: 'work',
    dependsOn: [],
    completedDate: new Date(new Date().setDate(new Date().getDate() - 1)),
  },
  {
    id: 'task-4',
    title: 'Design database schema for new feature',
    description: 'Outline the collections, fields, and relationships for the upcoming analytics module.',
    completed: false,
    priority: 'high',
    tags: ['development', 'database'],
    dueDate: new Date(),
    pomodoros: 2,
    completedPomodoros: 1,
    timeSpent: 1500,
    workspace: 'work',
    dependsOn: [],
    completedDate: undefined,
  },
  {
    id: 'task-5',
    title: 'Book annual dental check-up',
    description: 'Find a time that works and schedule an appointment with the dentist.',
    completed: false,
    priority: 'low',
    tags: ['health', 'personal'],
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)),
    pomodoros: 1,
    completedPomodoros: 0,
    timeSpent: 0,
    workspace: 'personal',
    dependsOn: [],
    completedDate: undefined,
  },
  {
    id: 'task-6',
    title: 'Plan weekend trip to the mountains',
    description: 'Research hiking trails, book accommodation, and plan the itinerary.',
    completed: false,
    priority: 'medium',
    tags: ['travel', 'personal'],
    dueDate: new Date(new Date().setDate(new Date().getDate() + 14)),
    pomodoros: 3,
    completedPomodoros: 0,
    timeSpent: 0,
    workspace: 'personal',
    dependsOn: [],
    completedDate: undefined,
  },
];
